apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: package-server-manager-metrics
  namespace: openshift-operator-lifecycle-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: package-server-manager-metrics.openshift-operator-lifecycle-manager.svc
  namespaceSelector:
    matchNames:
      - openshift-operator-lifecycle-manager
  selector: {}
