apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: package-server-manager-serving-cert
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
  name: package-server-manager-metrics
  namespace: openshift-operator-lifecycle-manager
spec:
  ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
  selector:
    app: package-server-manager
  sessionAffinity: None
  type: ClusterIP
