apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: openshift-operator-lifecycle-manager
  labels:
    prometheus: alert-rules
    role: alert-rules
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
spec:
  groups:
    - name: olm.csv_abnormal.rules
      rules:
        - alert: CsvAbnormalFailedOver2Min
          expr: last_over_time(csv_abnormal{phase="Failed"}[5m])
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: CSV failed for over 2 minutes
            description: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Reason-{{ $labels.reason }}
        - alert: CsvAbnormalOver30Min
          expr: last_over_time(csv_abnormal{phase=~"(Replacing|Pending|Deleting|Unknown)"}[5m])
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: CSV abnormal for over 30 minutes
            description: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Phase-{{ $labels.phase }} Reason-{{ $labels.reason }}
    - name: olm.installplan.rules
      rules:
        - alert: InstallPlanStepAppliedWithWarnings
          expr: sum by(namespace) (increase(installplan_warnings_total[5m])) > 0
          labels:
            severity: warning
          annotations:
            summary: API returned a warning when modifying an operator
            description: The API server returned a warning during installation or upgrade of an operator. An Event with reason "AppliedWithWarnings" has been created with complete details, including a reference to the InstallPlan step that generated the warning.
